version: '3.7'

services:
  prometheus:
    image: docker.io/prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"  # Exposes Prometheus web UI on port 9090
    volumes:
      - /u01/mydev/containers-fs-layout/prom-prometheus/etc/prometheus.yml:/etc/prometheus/prometheus.yml
      - /u01/mydev/containers-fs-layout/prom-prometheus/data:/prometheus
    restart: always
    networks:
      - mon-net

networks:
  mon-net:
    external:
      name: monitoring-network

volumes:
  prometheus_data:

